require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClosingDaysController do

  # This should return the minimal set of attributes required to create a valid
  # ClosingDay. As you add validations to ClosingDay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "time_table_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClosingDaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all closing_days as @closing_days" do
      closing_day = ClosingDay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:closing_days).should eq([closing_day])
    end
  end

  describe "GET show" do
    it "assigns the requested closing_day as @closing_day" do
      closing_day = ClosingDay.create! valid_attributes
      get :show, {:id => closing_day.to_param}, valid_session
      assigns(:closing_day).should eq(closing_day)
    end
  end

  describe "GET new" do
    it "assigns a new closing_day as @closing_day" do
      get :new, {}, valid_session
      assigns(:closing_day).should be_a_new(ClosingDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested closing_day as @closing_day" do
      closing_day = ClosingDay.create! valid_attributes
      get :edit, {:id => closing_day.to_param}, valid_session
      assigns(:closing_day).should eq(closing_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClosingDay" do
        expect {
          post :create, {:closing_day => valid_attributes}, valid_session
        }.to change(ClosingDay, :count).by(1)
      end

      it "assigns a newly created closing_day as @closing_day" do
        post :create, {:closing_day => valid_attributes}, valid_session
        assigns(:closing_day).should be_a(ClosingDay)
        assigns(:closing_day).should be_persisted
      end

      it "redirects to the created closing_day" do
        post :create, {:closing_day => valid_attributes}, valid_session
        response.should redirect_to(ClosingDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved closing_day as @closing_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClosingDay.any_instance.stub(:save).and_return(false)
        post :create, {:closing_day => { "time_table_id" => "invalid value" }}, valid_session
        assigns(:closing_day).should be_a_new(ClosingDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClosingDay.any_instance.stub(:save).and_return(false)
        post :create, {:closing_day => { "time_table_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested closing_day" do
        closing_day = ClosingDay.create! valid_attributes
        # Assuming there are no other closing_days in the database, this
        # specifies that the ClosingDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClosingDay.any_instance.should_receive(:update_attributes).with({ "time_table_id" => "1" })
        put :update, {:id => closing_day.to_param, :closing_day => { "time_table_id" => "1" }}, valid_session
      end

      it "assigns the requested closing_day as @closing_day" do
        closing_day = ClosingDay.create! valid_attributes
        put :update, {:id => closing_day.to_param, :closing_day => valid_attributes}, valid_session
        assigns(:closing_day).should eq(closing_day)
      end

      it "redirects to the closing_day" do
        closing_day = ClosingDay.create! valid_attributes
        put :update, {:id => closing_day.to_param, :closing_day => valid_attributes}, valid_session
        response.should redirect_to(closing_day)
      end
    end

    describe "with invalid params" do
      it "assigns the closing_day as @closing_day" do
        closing_day = ClosingDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClosingDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => closing_day.to_param, :closing_day => { "time_table_id" => "invalid value" }}, valid_session
        assigns(:closing_day).should eq(closing_day)
      end

      it "re-renders the 'edit' template" do
        closing_day = ClosingDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClosingDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => closing_day.to_param, :closing_day => { "time_table_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested closing_day" do
      closing_day = ClosingDay.create! valid_attributes
      expect {
        delete :destroy, {:id => closing_day.to_param}, valid_session
      }.to change(ClosingDay, :count).by(-1)
    end

    it "redirects to the closing_days list" do
      closing_day = ClosingDay.create! valid_attributes
      delete :destroy, {:id => closing_day.to_param}, valid_session
      response.should redirect_to(closing_days_url)
    end
  end

end
