require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeekClosingsController do

  # This should return the minimal set of attributes required to create a valid
  # WeekClosing. As you add validations to WeekClosing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "time_table_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeekClosingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all week_closings as @week_closings" do
      week_closing = WeekClosing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:week_closings).should eq([week_closing])
    end
  end

  describe "GET show" do
    it "assigns the requested week_closing as @week_closing" do
      week_closing = WeekClosing.create! valid_attributes
      get :show, {:id => week_closing.to_param}, valid_session
      assigns(:week_closing).should eq(week_closing)
    end
  end

  describe "GET new" do
    it "assigns a new week_closing as @week_closing" do
      get :new, {}, valid_session
      assigns(:week_closing).should be_a_new(WeekClosing)
    end
  end

  describe "GET edit" do
    it "assigns the requested week_closing as @week_closing" do
      week_closing = WeekClosing.create! valid_attributes
      get :edit, {:id => week_closing.to_param}, valid_session
      assigns(:week_closing).should eq(week_closing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WeekClosing" do
        expect {
          post :create, {:week_closing => valid_attributes}, valid_session
        }.to change(WeekClosing, :count).by(1)
      end

      it "assigns a newly created week_closing as @week_closing" do
        post :create, {:week_closing => valid_attributes}, valid_session
        assigns(:week_closing).should be_a(WeekClosing)
        assigns(:week_closing).should be_persisted
      end

      it "redirects to the created week_closing" do
        post :create, {:week_closing => valid_attributes}, valid_session
        response.should redirect_to(WeekClosing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved week_closing as @week_closing" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeekClosing.any_instance.stub(:save).and_return(false)
        post :create, {:week_closing => { "time_table_id" => "invalid value" }}, valid_session
        assigns(:week_closing).should be_a_new(WeekClosing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeekClosing.any_instance.stub(:save).and_return(false)
        post :create, {:week_closing => { "time_table_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested week_closing" do
        week_closing = WeekClosing.create! valid_attributes
        # Assuming there are no other week_closings in the database, this
        # specifies that the WeekClosing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WeekClosing.any_instance.should_receive(:update_attributes).with({ "time_table_id" => "1" })
        put :update, {:id => week_closing.to_param, :week_closing => { "time_table_id" => "1" }}, valid_session
      end

      it "assigns the requested week_closing as @week_closing" do
        week_closing = WeekClosing.create! valid_attributes
        put :update, {:id => week_closing.to_param, :week_closing => valid_attributes}, valid_session
        assigns(:week_closing).should eq(week_closing)
      end

      it "redirects to the week_closing" do
        week_closing = WeekClosing.create! valid_attributes
        put :update, {:id => week_closing.to_param, :week_closing => valid_attributes}, valid_session
        response.should redirect_to(week_closing)
      end
    end

    describe "with invalid params" do
      it "assigns the week_closing as @week_closing" do
        week_closing = WeekClosing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeekClosing.any_instance.stub(:save).and_return(false)
        put :update, {:id => week_closing.to_param, :week_closing => { "time_table_id" => "invalid value" }}, valid_session
        assigns(:week_closing).should eq(week_closing)
      end

      it "re-renders the 'edit' template" do
        week_closing = WeekClosing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeekClosing.any_instance.stub(:save).and_return(false)
        put :update, {:id => week_closing.to_param, :week_closing => { "time_table_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested week_closing" do
      week_closing = WeekClosing.create! valid_attributes
      expect {
        delete :destroy, {:id => week_closing.to_param}, valid_session
      }.to change(WeekClosing, :count).by(-1)
    end

    it "redirects to the week_closings list" do
      week_closing = WeekClosing.create! valid_attributes
      delete :destroy, {:id => week_closing.to_param}, valid_session
      response.should redirect_to(week_closings_url)
    end
  end

end
